local olua = require "olua.core"

function gen_header(module)
    local HEADER = string.upper(module.NAME)
    local MODULE_NAME = module.NAME
    olua.write(module.HEADER_PATH, olua.format([[
        //
        // generated by olua
        //
        #ifndef __AUTO_GEN_LUA_${HEADER}_H__
        #define __AUTO_GEN_LUA_${HEADER}_H__

        #include "xgame/xlua.h"

        LUALIB_API int luaopen_${MODULE_NAME}(lua_State *L);

        #endif
    ]]) .. '\n')
end