return {
    RUNTIME_PAUSE       = "runtimePause",
    RUNTIME_RESUME      = "runtimeResume",
    RUNTIME_UPDATE      = "runtimeUpdate",
    RUNTIME_RESIZE      = "runtimeResize",
    CHANGE              = "change",
    CANCEL              = "cancel",
    SELECT              = "select",
    CREATE              = "create",
    STOP                = "stop",
    COMPLETE            = "complete",
    PROGRESS            = "progress",
    IOERROR             = "ioerror",
    OPEN_URL            = "openURL",
    ADDED               = "added",
    REMOVED             = "removed",
    CREATION_COMPLETE   = "creationComplete",
    CLOSE               = "close",
    FOCUS_IN            = "focusIn",
    FOCUS_OUT           = "focusOut",
    ACTIVE              = "active",
    INACTIVE            = "inactive",
}
