//
// generated by olua
//
#ifndef __AUTO_GEN_LUA_FAIRYGUI_CONV_H__
#define __AUTO_GEN_LUA_FAIRYGUI_CONV_H__

#include "xgame/xlua.h"
#include "FairyGUI.h"

// fairygui::Margin
int auto_luacv_push_fairygui_Margin(lua_State *L, const fairygui::Margin *value);
void auto_luacv_check_fairygui_Margin(lua_State *L, int idx, fairygui::Margin *value);
void auto_luacv_opt_fairygui_Margin(lua_State *L, int idx, fairygui::Margin *value, const fairygui::Margin &def);
bool auto_luacv_is_fairygui_Margin(lua_State *L, int idx);

// fairygui::TweenValue
int auto_luacv_push_fairygui_TweenValue(lua_State *L, const fairygui::TweenValue *value);
void auto_luacv_check_fairygui_TweenValue(lua_State *L, int idx, fairygui::TweenValue *value);
void auto_luacv_opt_fairygui_TweenValue(lua_State *L, int idx, fairygui::TweenValue *value, const fairygui::TweenValue &def);
bool auto_luacv_is_fairygui_TweenValue(lua_State *L, int idx);

#endif