local M = {}
local cls = class(M)
cls.CPPCLS = "cocos2d::MATRIX_STACK_TYPE"
cls.LUACLS = "cc.MATRIX_STACK_TYPE"
cls.enum('MATRIX_STACK_MODELVIEW')
cls.enum('MATRIX_STACK_PROJECTION')
cls.enum('MATRIX_STACK_TEXTURE')

local cls = class(M)
cls.CPPCLS = "cocos2d::Director"
cls.LUACLS = "cc.Director"
cls.SUPERCLS = "cc.Ref"
cls.funcs([[
    static Director *getInstance()
    Scene* getRunningScene()
    float getAnimationInterval()
    void setAnimationInterval(float interval)
    bool isDisplayStats()
    void setDisplayStats(bool displayStats)
    float getSecondsPerFrame()
    GLView* getOpenGLView()
    void setOpenGLView(GLView *openGLView)
    TextureCache* getTextureCache()
    bool isNextDeltaTimeZero()
    void setNextDeltaTimeZero(bool nextDeltaTimeZero)
    bool isPaused()
    unsigned int getTotalFrames()
    Projection getProjection()
    void setProjection(Projection projection)
    void setViewport()
    bool isSendCleanupToScene()
    Node* getNotificationNode()
    void setNotificationNode(Node *node)
    @unpack const Size& getWinSize()
    @unpack Size getWinSizeInPixels()
    @unpack Size getVisibleSize()
    @unpack Vec2 getVisibleOrigin()
    @unpack Rect getSafeAreaRect()
    @unpack Vec2 convertToGL(@pack const Vec2& point)
    @unpack Vec2 convertToUI(@pack const Vec2& point)
    float getZEye()
    void runWithScene(Scene *scene)
    void pushScene(Scene *scene)
    void popScene()
    void popToRootScene()
    void popToSceneStackLevel(int level)
    void replaceScene(Scene *scene)
    void end()
    void pause()
    void resume()
    void restart()
    void stopAnimation()
    void startAnimation()
    void drawScene()
    void purgeCachedData()
    void setDefaultValues()
    void setGLDefaultValues()
    void setAlphaBlending(bool on)
    void setClearColor(const Color4F& clearColor)
    void setDepthTest(bool on);
    void mainLoop()
    void mainLoop(float dt)
    void setContentScaleFactor(float scaleFactor)
    float getContentScaleFactor()
    Scheduler* getScheduler()
    void setScheduler(Scheduler* scheduler)
    ActionManager* getActionManager()
    void setActionManager(ActionManager* actionManager)
    EventDispatcher* getEventDispatcher()
    void setEventDispatcher(EventDispatcher* dispatcher)
    Renderer* getRenderer()
    float getDeltaTime()
    float getFrameRate()
    void pushMatrix(MATRIX_STACK_TYPE type)
    void pushProjectionMatrix(size_t index)
    void popMatrix(MATRIX_STACK_TYPE type)
    void popProjectionMatrix(size_t index)
    void loadIdentityMatrix(MATRIX_STACK_TYPE type)
    void loadProjectionIdentityMatrix(size_t index)
    void loadMatrix(MATRIX_STACK_TYPE type, const Mat4& mat)
    void loadProjectionMatrix(const Mat4& mat, size_t index)
    void multiplyMatrix(MATRIX_STACK_TYPE type, const Mat4& mat)
    void multiplyProjectionMatrix(const Mat4& mat, size_t index)
    const Mat4& getMatrix(MATRIX_STACK_TYPE type)
    const Mat4& getProjectionMatrix(size_t index)
    void resetMatrixStack()
    void initProjectionMatrixStack(size_t stackCount)
    size_t getProjectionMatrixStackSize()
    bool isValid()
]])
cls.prop("runningScene")
cls.prop('animationInterval')
cls.prop('displayStats')
cls.prop('secondsPerFrame')
cls.prop('openGLView')
cls.prop('textureCache')
cls.prop('nextDeltaTimeZero')
cls.prop('paused')
cls.prop('totalFrames')
cls.prop('projection')
cls.prop('sendCleanupToScene')
cls.prop('notificationNode')
cls.prop('zEye')
cls.prop('contentScaleFactor')
cls.prop('scheduler')
cls.prop('actionManager')
cls.prop('renderer')
cls.prop('eventDispatcher')
cls.prop('deltaTime')
cls.prop('frameRate')
cls.prop('valid')
return M
