#ifndef __LUAUSER_H__
#define __LUAUSER_H__

#define OLUA_HAVE_MAINTHREAD
#define OLUA_HAVE_CHECKHOSTTHREAD
#define OLUA_HAVE_CMPREF
#define OLUA_HAVE_TRACEINVOKING
#define OLUA_HAVE_POSTPUSH
#define OLUA_HAVE_POSTNEW
//#define OLUA_HAVE_POSTGC
#define OLUA_HAVE_LUATYPE

#endif
