excludetype 'cocos2d::Console'
excludetype 'cocos2d::FontDefinition'
excludetype 'cocos2d::Font'
excludetype 'cocos2d::FontLetterDefinition'
excludetype 'cocos2d::GroupCommandManager'
excludetype 'cocos2d::MipmapInfo'
excludetype 'cocos2d::Physics3DWorld'
excludetype 'cocos2d::NavMesh'
excludetype 'cocos2d::PolygonInfo'
excludetype 'cocos2d::RenderCommand'
excludetype 'cocos2d::IMEKeyboardNotificationInfo'
excludetype 'cocos2d::Value **'
excludetype 'cocos2d::Tile'
excludetype 'cocos2d::Grabber'
excludetype 'va_list'
excludetype 'cpBody'
excludetype 'cocos2d::PhysicsContactData *'
excludetype 'cocos2d::SEL_SCHEDULE'
excludetype 'cocos2d::V3F_C4B_T2F_Quad'
excludetype 'cocos2d::_ccArray'
