excludetype 'cocos2d::Console *'
excludetype 'cocos2d::Font *'
excludetype 'cocos2d::FontDefinition'
excludetype 'cocos2d::Acceleration'
excludetype 'cocos2d::Font'
excludetype 'cocos2d::FontLetterDefinition'
excludetype 'cocos2d::GroupCommandManager *'
excludetype 'cocos2d::Mat4 *'
excludetype 'cocos2d::MipmapInfo *'
excludetype 'cocos2d::Physics3DWorld *'  -- TDDO
excludetype 'cocos2d::NavMesh *'         -- TDDO
excludetype 'cocos2d::PolygonInfo'
excludetype 'cocos2d::RenderCommand *'
excludetype 'cocos2d::IMEKeyboardNotificationInfo'
excludetype 'cocos2d::Vec2 *'
excludetype 'cocos2d::Vec3 *'
excludetype 'cocos2d::Vec4 *'
excludetype 'cocos2d::Quaternion *'
excludetype 'cocos2d::Value **'
excludetype 'cocos2d::Tile *'
excludetype 'cocos2d::Rect *'
excludetype 'cocos2d::Grabber *'
excludetype 'va_list'
excludetype 'float *'
excludetype 'GLfloat *'
excludetype 'GLint *'
excludetype 'std::vector *'
excludetype 'cocos2d::_ccArray *'
excludetype 'cpBody *'
excludetype 'cocos2d::PhysicsContactData *'

excludeany 'cocos2d::SEL_SCHEDULE'
excludeany 'cocos2d::V3F_C4B_T2F_Quad'