exclude 'cocos2d::Acceleration'
exclude 'cocos2d::Console::Command *'
exclude 'cocos2d::Console::Command'
exclude 'cocos2d::Font'
exclude 'cocos2d::Font *'
exclude 'cocos2d::FontDefinition'
exclude 'cocos2d::FontLetterDefinition'
exclude 'cocos2d::Grabber *'
exclude 'cocos2d::GroupCommandManager *'
exclude 'cocos2d::IMEKeyboardNotificationInfo'
exclude 'cocos2d::MipmapInfo *'
exclude 'cocos2d::NavMesh *'         -- TDDO
exclude 'cocos2d::Physics3DWorld *'  -- TDDO
exclude 'cocos2d::PolygonInfo'
exclude 'cocos2d::Quaternion *'
exclude 'cocos2d::RenderState::StateBlock'
exclude 'cocos2d::SEL_SCHEDULE'
exclude 'cocos2d::Tile *'
exclude 'cocos2d::V3F_C4B_T2F_Quad *'
exclude 'cocos2d::V3F_C4B_T2F_Quad'
exclude 'cocos2d::Value **'
exclude 'cocos2d::Vec2 *'
exclude 'cocos2d::Vec3 *'
exclude 'cocos2d::Vec4 *'
exclude 'char **'
exclude 'float *'
exclude 'GLfloat *'
exclude 'GLint *'
exclude 'int *'
exclude 'int16_t *'
exclude 'struct cocos2d::_ccArray *'
exclude 'uint16_t *'
exclude 'unsigned int *'
exclude 'unsigned short *'
exclude 'va_list'

exclude 'cpBody *'
exclude 'cocos2d::PhysicsContactData *'