//
// generated by olua
//
#ifndef __AUTO_GEN_LUA_CONV_H__
#define __AUTO_GEN_LUA_CONV_H__

#include "xgame/xlua.h"
#include "lua.hpp"

#include "cocos2d.h"

// cocos2d::Vec2
int auto_luacv_push_cocos2d_Vec2(lua_State *L, const cocos2d::Vec2 *value);
void auto_luacv_check_cocos2d_Vec2(lua_State *L, int idx, cocos2d::Vec2 *value);
void auto_luacv_pack_cocos2d_Vec2(lua_State *L, int idx, cocos2d::Vec2 *value);
int auto_luacv_unpack_cocos2d_Vec2(lua_State *L, const cocos2d::Vec2 *value);
bool auto_luacv_is_cocos2d_Vec2(lua_State *L, int idx);

// cocos2d::Vec3
int auto_luacv_push_cocos2d_Vec3(lua_State *L, const cocos2d::Vec3 *value);
void auto_luacv_check_cocos2d_Vec3(lua_State *L, int idx, cocos2d::Vec3 *value);
void auto_luacv_pack_cocos2d_Vec3(lua_State *L, int idx, cocos2d::Vec3 *value);
int auto_luacv_unpack_cocos2d_Vec3(lua_State *L, const cocos2d::Vec3 *value);
bool auto_luacv_is_cocos2d_Vec3(lua_State *L, int idx);

// cocos2d::Vec4
int auto_luacv_push_cocos2d_Vec4(lua_State *L, const cocos2d::Vec4 *value);
void auto_luacv_check_cocos2d_Vec4(lua_State *L, int idx, cocos2d::Vec4 *value);
void auto_luacv_pack_cocos2d_Vec4(lua_State *L, int idx, cocos2d::Vec4 *value);
int auto_luacv_unpack_cocos2d_Vec4(lua_State *L, const cocos2d::Vec4 *value);
bool auto_luacv_is_cocos2d_Vec4(lua_State *L, int idx);

// cocos2d::Size
int auto_luacv_push_cocos2d_Size(lua_State *L, const cocos2d::Size *value);
void auto_luacv_check_cocos2d_Size(lua_State *L, int idx, cocos2d::Size *value);
void auto_luacv_pack_cocos2d_Size(lua_State *L, int idx, cocos2d::Size *value);
int auto_luacv_unpack_cocos2d_Size(lua_State *L, const cocos2d::Size *value);
bool auto_luacv_is_cocos2d_Size(lua_State *L, int idx);

// cocos2d::Texture2D::TexParams
int auto_luacv_push_cocos2d_Texture2D_TexParams(lua_State *L, const cocos2d::Texture2D::TexParams *value);
void auto_luacv_check_cocos2d_Texture2D_TexParams(lua_State *L, int idx, cocos2d::Texture2D::TexParams *value);
void auto_luacv_pack_cocos2d_Texture2D_TexParams(lua_State *L, int idx, cocos2d::Texture2D::TexParams *value);
int auto_luacv_unpack_cocos2d_Texture2D_TexParams(lua_State *L, const cocos2d::Texture2D::TexParams *value);
bool auto_luacv_is_cocos2d_Texture2D_TexParams(lua_State *L, int idx);

// cocos2d::Uniform
int auto_luacv_push_cocos2d_Uniform(lua_State *L, const cocos2d::Uniform *value);
void auto_luacv_check_cocos2d_Uniform(lua_State *L, int idx, cocos2d::Uniform *value);
void auto_luacv_pack_cocos2d_Uniform(lua_State *L, int idx, cocos2d::Uniform *value);
int auto_luacv_unpack_cocos2d_Uniform(lua_State *L, const cocos2d::Uniform *value);
bool auto_luacv_is_cocos2d_Uniform(lua_State *L, int idx);

// cocos2d::VertexAttrib
int auto_luacv_push_cocos2d_VertexAttrib(lua_State *L, const cocos2d::VertexAttrib *value);
void auto_luacv_check_cocos2d_VertexAttrib(lua_State *L, int idx, cocos2d::VertexAttrib *value);
void auto_luacv_pack_cocos2d_VertexAttrib(lua_State *L, int idx, cocos2d::VertexAttrib *value);
int auto_luacv_unpack_cocos2d_VertexAttrib(lua_State *L, const cocos2d::VertexAttrib *value);
bool auto_luacv_is_cocos2d_VertexAttrib(lua_State *L, int idx);

// cocos2d::experimental::Viewport
int auto_luacv_push_cocos2d_experimental_Viewport(lua_State *L, const cocos2d::experimental::Viewport *value);
void auto_luacv_check_cocos2d_experimental_Viewport(lua_State *L, int idx, cocos2d::experimental::Viewport *value);
void auto_luacv_pack_cocos2d_experimental_Viewport(lua_State *L, int idx, cocos2d::experimental::Viewport *value);
int auto_luacv_unpack_cocos2d_experimental_Viewport(lua_State *L, const cocos2d::experimental::Viewport *value);
bool auto_luacv_is_cocos2d_experimental_Viewport(lua_State *L, int idx);

#endif