return {
    RUNTIME_PAUSE       = "runtimePause",
    RUNTIME_RESUME      = "runtimeResume",
    AFTER_UPDATE        = "afterUpdate",
    AFTER_DRAW          = "afterDraw",
    PROJECTION_CHANGED  = "projectionChanged",
    CHANGE              = "change",
    CANCEL              = "cancel",
    SELECT              = "select",
    CREATE              = "create",
    STOP                = "stop",
    COMPLETE            = "complete",
    PROGRESS            = "progress",
    IOERROR             = "ioerror",
    OPEN_URL            = "openURL",
    ADDED_TO_STAGE      = "addedToStage",
    REMOVED_FORM_STAGE  = "removedFromStage",
    CREATION_COMPLETE   = "creationComplete",
    CLOSE               = "close",
    FOCUS_IN            = "focusIn",
    FOCUS_OUT           = "focusOut",
    ACTIVE              = "active",
    INACTIVE            = "inactive",
}
